# Generated by Django 5.2 on 2025-04-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.category'),
        ),
    ]
