# Generated by Django 5.2 on 2025-05-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ticket'),
        ('app', '0010_event_venue'),
    ]

    operations = [
    ]
