# Generated by Django 5.2 on 2025-05-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('AVAILABLE', 'Activo'), ('CANCELLED', 'Cancelado'), ('REPROGRAM', 'Reprogramado'), ('SOLD_OUT', 'Agotado'), ('FINISHED', 'Finalizado')], default='AVAILABLE', max_length=20),
        ),
    ]
