# Generated by Django 5.2 on 2025-05-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='general_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
