# Generated by Django 5.2 on 2025-05-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_general_capacity_event_vip_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
