# Generated by Django 5.2 on 2025-05-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_state'),
        ('app', '0016_remove_event_capacity'),
    ]

    operations = [
    ]
