# Generated by Django 5.2 on 2025-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_0014_event_state_0016_remove_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='general_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_capacity',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
